import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = localFont({
  src: [
    {
      path: '../../public/fonts/pxiEyp8kv8JHgFVrJJbecmNE.woff2',
      weight: '400'
    },
    {
      path: '../../public/fonts/pxiEyp8kv8JHgFVrJJfecg.woff2',
      weight: '700'
    }
  ],
  variable: '--font-poppins'
})



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${poppins.variable} font-sans`}>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
